language: generic 
sudo: required
# Anytime we are making use of docker, we have to have superuser permissions in order to execute this build
services: 
  - docker # We need the docker CLI pre-installed. Travis will automatically install a copy of docker into the container.

before-install: 
  # It is going to have a series of different commands that get executed before our tests are ran.
  # It will be a series of setups that needs to occur before we start to either deploy our project or before running tests
  docker build -t xholyspirit/docker-react-course -f Dockerfile.dev .

script:
  # The script section will contain all the different commands that need to be executed to run the test suites
  # Travis CI will watch the output from each of the command, and if one of the commands returns status code other than zero,
  # Travis is going to assume that our build failed, or our test suite failed to run properly
  # Anytime that we run our test suite on Travis CI, Travis is going to assume that our test suites runs and exit automatically.
  # Need to add in a flag so that the test suite automatically exits the instance the first run is completed
  - docker run -e CI=true xholyspirit/docker-react-course npm run test -- --coverage